# Generated by Django 5.2.1 on 2025-06-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Varição', 'verbose_name_plural': 'Variações'},
        ),
    ]
