# Generated by Django 5.2.1 on 2025-06-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_sulg_alter_produto_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='sulg',
            new_name='slug',
        ),
    ]
